imap:
  server: "imap.example.com"
  port: 993
  username: "user@example.com"

# Spam filter settings
spam_filter:
  check_interval: 60                # Check interval in seconds

# REST API server configuration
server:
  host: "0.0.0.0"                  # Bind to all network interfaces
  port: 3000